[package]
name = "trusty_frontend"
version = "0.1.0"
authors = ["BookOwl <stanleybookowl@gmail.com>"]
license = "MIT"

[dependencies]
trusty_utils = { git = "https://github.com/trusty-editor/utils" }
